# Used in GitHub CI.
# Don't use this config to run the service in production.

version: "3"
volumes:
  database: {}
services:
  db:
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    image: postgres:12.2
    volumes:
      - database:/var/lib/postgresql/data
  app:
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DB_TEST_HOST=${DB_TEST_HOST}
      - DB_TEST_USERNAME=${DB_TEST_USERNAME}
    image: chrztoph/texterify:test
    build:
      context: .
      args:
        SENTRY_SOURCE_MAPS_ORGANIZATION: texterify
        COMMIT_HASH: ${GITHUB_SHA}
        PROPRIETARY_MODE: "true"
        RAILS_ENV_ARG: test
        NODE_ENV_ARG: production
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./coverage:/var/www/texterify/coverage
  sidekiq:
    image: chrztoph/texterify:test
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DB_TEST_HOST=${DB_TEST_HOST}
      - DB_TEST_USERNAME=${DB_TEST_USERNAME}
    depends_on:
      - db
      - redis
    command: bundle exec sidekiq

  redis:
    image: redis:6.2.0-alpine
