name: Test

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        version: ["latest"]
    steps:
      - uses: actions/checkout@v2

      - name: Create docker volume texterify-database
        run: docker volume create --name=texterify-database

      - name: Create docker volume texterify-assets
        run: docker volume create --name=texterify-assets

      - name: Run docker-compose
        run: RAILS_ENV=test TEXTERIFY_TAG=${{ matrix.version }} docker-compose up -d

      - name: Create and seed test database
        run: docker-compose exec -T app bundle exec rails db:create db:migrate db:seed RAILS_ENV=test

      - name: Install test dependencies in app
        run: docker-compose exec -T app bundle install --with test

      - name: Install dependencies
        run: yarn

      - name: docker ps
        run: docker ps

      - name: Run tests
        run: yarn test

      - name: Output docker app logs
        if: always()
        run: docker logs texterify-cli_app_1

      - name: Output docker db logs
        if: always()
        run: docker logs texterify-cli_db_1
